<a href="https://colab.research.google.com/github/Hruthikaveldi/23CSBTB29/blob/main/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [4]:
arry=np.array([2,5,7,3,8])
print(arry)
print(type(arry))

[2 5 7 3 8]
<class 'numpy.ndarray'>


In [9]:
array = np.array([2, 5, 7, 3, 8])
print("NumPy Array:", array)
print("Type:", type(array))
print("First element:", array[0])
print("Last element:", array[-1])
print("Sum of elements:", np.sum(array))
print("Mean of elements:", np.mean(array))

NumPy Array: [2 5 7 3 8]
Type: <class 'numpy.ndarray'>
First element: 2
Last element: 8
Sum of elements: 25
Mean of elements: 5.0


In [13]:
array = np.array([2, 5, 7, 3, 8])
print("Array:", array)
print("Type of array:", type(array))
print("First element:", array[0])
print("Last element:", array[-1])

Array: [2 5 7 3 8]
Type of array: <class 'numpy.ndarray'>
First element: 2
Last element: 8


In [14]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
print("Type of 1D Array:", type(array_1d))
print("Sum of elements:", np.sum(array_1d))
print("Mean of elements:", np.mean(array_1d))


1D Array: [1 2 3 4 5]
Type of 1D Array: <class 'numpy.ndarray'>
Sum of elements: 15
Mean of elements: 3.0


In [15]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", array_2d)
print("Type of 2D Array:", type(array_2d))
print("Sum of elements in 2D array:", np.sum(array_2d))
print("Transpose of 2D array:\n", np.transpose(array_2d))


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type of 2D Array: <class 'numpy.ndarray'>
Sum of elements in 2D array: 45
Transpose of 2D array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print("3D Array:\n", array_3d)
print("Type of 3D Array:", type(array_3d))
print("Sum of elements in 3D array:", np.sum(array_3d))
print("Shape of 3D array:", array_3d.shape)


3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Type of 3D Array: <class 'numpy.ndarray'>
Sum of elements in 3D array: 78
Shape of 3D array: (2, 2, 3)


In [19]:
# Creating a 4D array
array_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
                     [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print("4D Array:\n", array_4d)
print("Type of 4D Array:", type(array_4d))
print("Sum of elements in 4D array:", np.sum(array_4d))
print("Shape of 4D array:", array_4d.shape)


4D Array:
 [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Type of 4D Array: <class 'numpy.ndarray'>
Sum of elements in 4D array: 136
Shape of 4D array: (2, 2, 2, 2)


In [20]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
array_add = array_a + array_b
print("\nAddition of Two Arrays:", array_add)
array_mul = array_a * array_b
print("Multiplication of Two Arrays:", array_mul)
array_div = array_b / array_a
print("Division of Two Arrays:", array_div)
array_pow = np.power(array_a, 2)
print("Element-wise Power (array_a^2):", array_pow)



Addition of Two Arrays: [5 7 9]
Multiplication of Two Arrays: [ 4 10 18]
Division of Two Arrays: [4.  2.5 2. ]
Element-wise Power (array_a^2): [1 4 9]


In [23]:
sin_values = np.sin(array_a)
print("\nSin of array_a:", sin_values)
log_values = np.log(array_b)
print("Log of array_b:", log_values)
log2_values = np.log2(array_b)
print("Log base-2 of array_b:", log2_values)
exp_values = np.exp(array_a)
print("Exponential of array_a:", exp_values)



Sin of array_a: [0.84147098 0.90929743 0.14112001]
Log of array_b: [1.38629436 1.60943791 1.79175947]
Log base-2 of array_b: [2.         2.32192809 2.5849625 ]
Exponential of array_a: [ 2.71828183  7.3890561  20.08553692]
